package com.demo.springreact.response;

public enum ResponseStatus {
    JOIN_SUCCESS, JOIN_FAIL,
    LOGIN_SUCCESS, LOGIN_FAIL,
    LOAD_MEMBERS_SUCCESS, LOAD_MEMBERS_FAIL,
    LOAD_CHATTING_ROOM_SUCCESS, LOAD_CHATTING_ROOM_FAIL,
    AUTHENTICATED, NOT_AUTHENTICATED,
    CREATED, NOT_CREATE,


}